version: '3.8'

services:
  things-to-draw-be:
    container_name: things-to-draw-be
    build: ./
    command: npm run start
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
